[package]
name = "example"
version = "0.1.0"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]

[dependencies]
diesel = "0.8.0"
diesel_codegen = { version = "0.8.0", features = ["postgres"] }
dotenv = "0.8.0"

iron = "*"
router = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"